replicaCount: 3

image:
  repository: cw1797/reverse-ip
  pullPolicy: IfNotPresent
  tag: 1b968274cc008d568487f2a5ea1b3f533d5f7fa2

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  ingressClassName: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: k8s-demo-reversei-f2e59279c6-1197832907.eu-west-1.elb.amazonaws.com
      paths:
        - path: /
          pathType: ImplementationSpecific

