name: Build and Push Docker image
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: app/
        push: true
        tags: cw1797/reverse-ip:${{ github.sha }}

    - name: Update Kubernetes deployment
      run: |
        sed -i 's|tag: .*|tag: ${{ github.sha }}|' helm/values.yaml
        sed -i 's|cw1797/reverse-ip:.*|cw1797/reverse-ip:${{ github.sha }}|' helm/values.yaml
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add argocd/deployment.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push origin main
